---
name: Feature Request
about: Suggest an interesting feature idea for this project
title: "feat(auth): write a suitable title all in lowercase"
labels: "feat"
assignees: ""
---

## **Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Ex: “I'm always frustrated when [...]”

## **Describe the solution you'd like**
A clear and concise description of what you want to happen.

## **Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

## **Screenshots (if appropriate — Postman, etc.)**
*Add screenshots or visual references if needed.*

## **Additional context**
Add any other context or related information here.